name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: finchannel
    contracts:
      - id: finchannelbs

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "User1"
          clientPrivateKey:
            pem: |-
              -----BEGIN PRIVATE KEY-----
              MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggbqI0Rx8Kd2JvB+H
              iycgYuXGelp68A64ZeOlEkbkdgShRANCAAQeo9+AsIcdWE7WadvSb0NPsnn59G0O
              dBoMNhlIpo3N7Ob2ytiU0Z56VcFpWx2wIXOcTZ2IgeeYgj6nmJ9DUxLG
              -----END PRIVATE KEY-----
          clientSignedCert:
            pem: |-
              -----BEGIN CERTIFICATE-----
              MIICKTCCAdCgAwIBAgIQN3FgYOsShmE7wBl0IN5kODAKBggqhkjOPQQDAjBzMQsw
              CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
              YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
              b3JnMS5leGFtcGxlLmNvbTAeFw0yMzA1MjExNjM0MDBaFw0zMzA1MTgxNjM0MDBa
              MGwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
              YW4gRnJhbmNpc2NvMQ8wDQYDVQQLEwZjbGllbnQxHzAdBgNVBAMMFlVzZXIxQG9y
              ZzEuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQeo9+AsIcd
              WE7WadvSb0NPsnn59G0OdBoMNhlIpo3N7Ob2ytiU0Z56VcFpWx2wIXOcTZ2IgeeY
              gj6nmJ9DUxLGo00wSzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADArBgNV
              HSMEJDAigCC/m6o1Lbalkgq56oWifbH15C+ctqnQZ4/axmPcm+adRDAKBggqhkjO
              PQQDAgNHADBEAiBIXocXE5NYFcifmFhZ42bQzN4YJXjoHcEb3TE3SAsksQIgS5+Y
              5sd/HvN0giaciwz3wECshK4T7/eEXXGvgo6dZcM=
              -----END CERTIFICATE-----
    connectionProfile:
      path: "../test-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true